const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{execFileSync}=require('node:child_process');
const {chromium}=require('C:/Users/林弘昇/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),base='ad08944b715befd3189b8ff171498b7697f63472';
for(const file of ['px-promo-core.js','px-promo-prices.json','px-promo-prices.js','px-product-additions.json','px-product-additions.js','px-sales-data.js','px-replacement-data.js','assets/brand/px-logo.svg','assets/brand/px-icon.svg','favicon.png','favicon-16.png','icon-192.png','icon-512.png']){const a=fs.readFileSync(path.join(root,file)),b=execFileSync('git',['show',base+':'+file]);assert.ok(file.endsWith('.png')?a.equals(b):a.toString().replace(/\r\n/g,'\n')===b.toString().replace(/\r\n/g,'\n'),file+' unchanged');}
const current=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/\r\n/g,'\n'),original=execFileSync('git',['show',base+':index.html'],{encoding:'utf8'}).replace(/\r\n/g,'\n');
assert.equal(current.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1],original.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1]);
// Calculator and replacement formulas remain identical; presentation hooks may change independently.
for(const [start,end] of [['function compareReplacementEffect(','function model('],['function model(','function rows('],['function calcC(','function calcR('],['function promoAverage(','function calcP(']])assert.equal(current.slice(current.indexOf(start),current.indexOf(end)),original.slice(original.indexOf(start),original.indexOf(end)),`${start} unchanged`);
const promoCore='const t=$("promoType").value,cost=n("pCost"),px=pct(n("pPx")),fee=pct(n("pFee")),a=n("pA"),avg=promoAverage(t,a),o=model(avg,cost,px,fee)';assert.ok(current.includes(promoCore)&&original.includes(promoCore),'promotion calculation source unchanged');
const reverseFormula=source=>source.match(/function calcR\(\)\{([\s\S]*?);\$\("rRows"\)\.innerHTML=rows\(o\)/)?.[1];
assert.ok(reverseFormula(current));assert.equal(reverseFormula(current),reverseFormula(original),'reverse formula unchanged');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html');if(!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.json':'application/json'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[],retailerRequests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>{if(r.url().includes('uni-prosperity'))retailerRequests.push(r.url())});
await page.goto(process.env.PX_LIVE||`http://127.0.0.1:${server.address().port}/index.html`,{waitUntil:'networkidle'});await page.locator('[data-tab="campaign"]').click();
const outcomes=[];
for(const [query,own,competitors] of [["保鮮膜",2,14],["妙潔",0,require("../competitor-prices.json").filter(p=>p.brand==="妙潔").length],["楓康",0,12],["30CM*55M",0,1],["86210115",1,14],["4710660882088",1,14],["OP植材抗菌保鮮膜300尺",1,14],["鋁箔",2,8],["指尖",2,require("../competitor-prices.json").filter(p=>p.category==="GLOVES").length],["膜",2,14],["OP保鮮膜",2,14]]){await page.locator('#campaignSearch').fill(query);assert.equal(await page.locator('#campaignResults .campaign-result').count(),own,query+' own');assert.equal(await page.locator('#competitorResults .competitor-card').count(),competitors,query+' competitors');outcomes.push({query,status:'PASS'});}
await page.locator('#campaignSearch').fill('保鮮膜');
const live=await page.evaluate(()=>COMPETITOR_DATA.records.filter(p=>p.category==='CLING_FILM'));assert.equal(live.length,14);for(const p of live){assert.equal(p.category,'CLING_FILM');assert.ok(p.currentPrice>0&&p.lastSuccessAt&&p.sourceUrl);}
const text=await page.locator('#competitorResults').innerText();assert.match(text,/原始售價/);assert.match(text,/寬度未提供/);assert.match(text,/選擇一支 OP 商品即可比較差額/);assert.ok(!text.includes('最後成功更新'),'timestamps are collapsed');await page.locator('#competitorResults .competitor-details summary').first().click();assert.match(await page.locator('#competitorResults').innerText(),/最後成功更新/);await page.locator('#competitorResults .competitor-details summary').first().click();assert.ok(!/即時价格|即時價格|最便宜|最划算|推薦/.test(text));
const links=await page.locator('#competitorResults .competitor-source-link').evaluateAll(elements=>elements.map(e=>e.href));assert.deepEqual([...links].sort(),live.map(p=>p.sourceUrl).sort());
const list=()=>page.locator('#competitorResults .competitor-card').evaluateAll(es=>es.map(e=>e.dataset.competitorId));
for(const [sort,field] of [['per10m','pricePer10M'],['area','pricePerSquareMeter']]){await page.locator('#competitorResults select').selectOption(sort);const ids=await list();for(const own of [true,false]){const values=ids.map(id=>live.find(p=>p.competitorProductId===id)).filter(p=>(p.brand==='OP')===own).map(p=>p[field]);assert.deepEqual(values,[...values].sort((a,b)=>(a===null)-(b===null)||(a??0)-(b??0)));}const flags=ids.map(id=>live.find(p=>p.competitorProductId===id).brand==='OP');assert.ok(flags.slice(flags.indexOf(false)).every(flag=>!flag),'OP priority before per-unit ordering');}
await page.locator('#competitorResults select').selectOption('default');assert.deepEqual(await list(),await page.evaluate(()=>[...competitorSorted(COMPETITOR_DATA.records.filter(p=>p.category==='CLING_FILM')).filter(p=>p.brand==='OP'),...competitorSorted(COMPETITOR_DATA.records.filter(p=>p.category==='CLING_FILM')).filter(p=>p.brand!=='OP')].map(p=>p.competitorProductId)));
await page.locator('[data-tab="calc"]').click();await page.locator('#cProduct').fill('86210115');assert.equal(await page.locator('#cCost').inputValue(),'43.52');assert.equal(await page.locator('#cProductInfo .competitor-card').count(),14);await page.locator('#cCost').fill('40.25');assert.equal(await page.locator('#cCost').inputValue(),'40.25');await page.locator('#cProduct').focus();await page.locator('#cProduct').fill('65010209');assert.equal(await page.locator('#cProductInfo .competitor-card').count(),8);
await page.locator('[data-tab="campaign"]').click();await page.locator('#campaignSearch').fill('保鮮膜');
await page.evaluate(()=>{const p=COMPETITOR_DATA.records[0];competitorRuntime[p.competitorProductId]={sourceStatus:'FAILED',lastSuccessAt:p.lastSuccessAt,reason:'HTTP_404'};refreshCompetitors()});const failed=page.locator('#competitorResults .competitor-card').filter({has:page.locator('[data-source-status="FAILED"]')});assert.match(await failed.innerText(),/資料待更新/);await failed.locator('summary').click();assert.match(await failed.innerText(),/來源頁目前無法開啟/);assert.match(await failed.innerText(),/\$69/);await failed.locator('summary').click();
let maximum=0;const viewports=[[320,568],[360,800],[375,667],[390,844],[393,852],[430,932],[768,1024],[820,1180],[1024,768],[1280,720],[1366,768],[1440,900],[1920,1080],[844,390]],rwd=[];
for(const [width,height] of viewports){await page.setViewportSize({width,height});const overflow=await page.evaluate(()=>Math.max(0,document.documentElement.scrollWidth-innerWidth));maximum=Math.max(maximum,overflow);assert.equal(overflow,0,width+'x'+height);rwd.push({viewport:width+'x'+height,status:'PASS'});}
await page.setViewportSize({width:390,height:844});await page.locator('#competitorResults .competitor-details summary').first().click();assert.match(await page.locator('#competitorResults').innerText(),/不扣滿額券/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);
await page.locator('#campaignSearch').fill('');assert.equal(await page.locator('#competitorResults .competitor-card').count(),0);
const cache=await page.evaluate(async()=>{await navigator.serviceWorker.ready;return caches.keys()});assert.deepEqual(cache,['px-workbench-v4.1.14-sales22']);assert.deepEqual(errors,[]);assert.deepEqual(retailerRequests,[]);
await page.evaluate(()=>{delete competitorRuntime[COMPETITOR_DATA.records[0].competitorProductId]});await page.locator('#campaignSearch').fill('保鮮膜');if(!process.env.PX_LIVE)await page.screenshot({path:path.join(root,'tests/competitor-mobile.png'),fullPage:true});console.log(JSON.stringify({status:'PASS',outcomes,rwd,maximumOverflow:maximum,consoleErrors:errors,retailerFrontendRequests:retailerRequests,protectedData:'UNCHANGED',products:live},null,2));await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
