const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),{execFileSync}=require('node:child_process');
const {chromium}=require('C:/Users/林弘昇/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),base='2d7593ed09351e6413b32dd191b9a5b76afb2940',html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/\r\n/g,'\n'),oldHtml=execFileSync('git',['show',base+':index.html'],{encoding:'utf8'}).replace(/\r\n/g,'\n');
for(const [from,to] of [['function model(','function rows('],['function calcC(','function calcR('],['function calcR(','const SCENARIO_CONFIG='],['function calcP(','function analyzePxSales(']])assert.equal(html.slice(html.indexOf(from),html.indexOf(to)),oldHtml.slice(oldHtml.indexOf(from),oldHtml.indexOf(to)),from+' unchanged');
assert.equal(html.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1],oldHtml.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1]);
for(const file of ['px-sales-data.js','px-replacement-data.js','px-promo-core.js'])assert.equal(fs.readFileSync(path.join(root,file),'utf8').replace(/\r\n/g,'\n'),execFileSync('git',['show',base+':'+file],{encoding:'utf8'}).replace(/\r\n/g,'\n'),file+' unchanged');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html');if(!fs.existsSync(file)){res.writeHead(404).end();return}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']}),page=await context.newPage(),errors=[];
 page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
 await page.goto(`http://127.0.0.1:${server.address().port}/index.html`,{waitUntil:'networkidle'});await page.locator('[data-tab="scenario"]').click();
 const decision=page.locator('#decisionSummary'),notices=()=>decision.locator('#decisionNotices').innerText();
 assert.deepEqual(await decision.locator('h4').allTextContents(),['目前需要注意','可進一步確認']);
 assert.match(await notices(),/目前資料不足，暫不判讀/);
 await page.locator('#sProduct').fill('65010209');await page.locator('#sPriceA').fill('62');await page.locator('#sPrice').fill('77');await page.locator('#sPriceC').fill('90');
 assert.match(await notices(),/目前中科毛利率低於設定門檻/);assert.match(await notices(),/B 方案較 A 方案改善/);assert.match(await notices(),/C 方案較 A 方案改善/);
 assert.match(await decision.locator('#decisionNext').innerText(),/可進一步比較不同售價／商品成本條件下的結果/);
 assert.doesNotMatch(await decision.innerText(),/\d+(?:\.\d+)?%|個百分點|B vs A|C vs A|全聯毛利率（前毛）/,'decision UI does not repeat the comparison figures');
 const originalCards=await page.locator('#scenarioResults .scenario-card').allInnerTexts();
 await page.locator('#copyDecisionSummary').click();let copied=await page.evaluate(()=>navigator.clipboard.readText());
 for(const text of ['【PX 商品決策摘要】','商品：OP無雙酚A鋁箔800公分-12入','條碼：4710660884433','目前需要注意','可進一步確認',await decision.locator('#decisionNext').innerText()])assert.ok(copied.includes(text),text);
 for(const text of await decision.locator('#decisionNotices li').allTextContents())assert.ok(copied.includes(text),'copy mirrors displayed notice');
 assert.doesNotMatch(copied,/中科毛利率（費用後）：|全聯毛利率（前毛）：|B vs A|C vs A|個百分點/);
 assert.deepEqual(await page.locator('#scenarioResults .scenario-card').allInnerTexts(),originalCards,'copy cannot alter source results');
 await page.locator('#sPriceC').fill('');assert.match(await notices(),/C 方案資料不足，暫不判讀/);await page.locator('#sPriceC').fill('90');
 await page.locator('#sPrice').fill('62');assert.match(await notices(),/B 方案與 A 方案持平/);await page.locator('#sPrice').fill('60');assert.match(await notices(),/B 方案低於 A 方案/);await page.locator('#sPrice').fill('77');
 await page.locator('#sCost').fill('24.50');assert.equal(await page.locator('#scenarioResults .scenario-card').first().locator('.scenario-final b').innerText(),await page.locator('#scenarioSummary [data-plan="A"] strong').innerText());
 await page.locator('#sPriceA').fill('90');assert.match(await notices(),/目前中科毛利率已達設定門檻/);await page.locator('#sPriceA').fill('62');
 await page.locator('[data-tab="calc"]').click();await page.locator('#thresholdSettings').evaluate(element=>{element.open=true});await page.locator('#excellentMargin').fill('50');await page.locator('#targetMargin').fill('45');await page.locator('[data-tab="scenario"]').click();assert.match(await notices(),/目前中科毛利率低於設定門檻/);
 await page.locator('#sProduct').fill('OP天然棉紗布(3片入)');assert.match(await notices(),/目前資料不足，暫不判讀/);await page.locator('#copyDecisionSummary').click();copied=await page.evaluate(()=>navigator.clipboard.readText());assert.match(copied,/商品：OP天然棉紗布\(3片入\)/);assert.doesNotMatch(copied,/OP無雙酚A鋁箔800公分-12入|NaN|undefined/);
 await page.locator('#sProduct').fill('65010209');await page.locator('[data-tab="calc"]').click();await page.locator('#cProduct').fill('OP指尖強化手套-薰衣紫M');await page.locator('[data-tab="scenario"]').click();assert.match(await notices(),/目前中科毛利率低於設定門檻/);
 const before=await decision.innerText();for(const tab of ['calc','reverse','promo','basis','campaign','scenario'])await page.locator(`[data-tab="${tab}"]`).click();assert.equal(await decision.innerText(),before);
 assert.doesNotMatch(await decision.innerText(),/建議採用|推薦|最佳方案|最划算|應該選|應該做|不值得做|值得做|一定要|最優解|\bNaN\b|undefined/);
 let overflow=0;for(const [width,height] of [[320,568],[360,800],[375,667],[390,844],[393,852],[430,932],[768,1024],[1280,720]]){await page.setViewportSize({width,height});overflow=Math.max(overflow,await page.evaluate(()=>Math.max(0,document.documentElement.scrollWidth-innerWidth)))}
 assert.equal(overflow,0);assert.deepEqual(errors,[]);
 await page.setViewportSize({width:390,height:844});await decision.screenshot({path:path.join(os.tmpdir(),'px-decision-summary-compact.png')});
 console.log(JSON.stringify({status:'PASS',twoSections:'PASS',sourceSync:'PASS',copy:'PASS',productSwitch:'PASS',otherTabs:'PASS',maximumOverflow:overflow,consoleErrors:errors},null,2));await browser.close();server.close();
})().catch(error=>{console.error(error);server.close();process.exit(1)});
