const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),http=require('node:http'),{execFileSync}=require('node:child_process');
// Prices remain in the existing collapsed campaign-details layer after lookup UI refinement.
const campaignText=async(page)=>{const details=page.locator('.lookup-campaign-details');if(await details.count()&&!await details.evaluate(el=>el.open))await details.locator(':scope > summary').click();return page.locator('#campaignResults').innerText()};
const core=require('../px-promo-core'),{importRows}=require('../scripts/import_px_promos.cjs'),data=require('../px-promo-prices.json'),report=require('../PX_PROMO_VALIDATION.json');
const {chromium}=require('C:/Users/林弘昇/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),baseline=JSON.parse(execFileSync('git',['show','c758b45:px-promo-prices.json'],{encoding:'utf8'}));
const master=vm.runInNewContext(fs.readFileSync(path.join(root,'index.html'),'utf8').match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1]),additions=require('../px-product-additions.json'),all=[...master,...additions],byBarcode=b=>data.products.find(p=>p.barcode===b),nov=p=>p.periods['2026-11-1'];
for(const old of baseline.products){const now=data.products.find(p=>p.productName===old.productName);for(const [id,value] of Object.entries(old.periods))assert.deepEqual(now.periods[id],value,'October history unchanged');}
assert.deepEqual(core.periods(data).map(p=>[p.id,p.startDate,p.endDate]),[['2026-10-1','2026-10-02','2026-10-15'],['2026-10-2','2026-10-16','2026-10-29'],['2026-11-1','2026-10-30','2026-11-19'],['2026-11-2','2026-11-20','2026-12-03']]);
assert.equal(data.products.flatMap(p=>Object.values(p.periods)).length,214);assert.equal(report.importedProducts,54);assert.equal(report.successfulPeriods,108);assert.equal(report.errorCount,0);assert.deepEqual(report.matchMethods,{CODE:52,BARCODE:2,NAME:0});
const cotton=byBarcode('4710660888820');assert.equal(all.filter(p=>p.barcode===cotton.barcode).length,1);assert.equal(cotton.productName,'OP天然棉紗布(3片入)');assert.equal(nov(cotton).matchMethod,'BARCODE');assert.equal(nov(cotton).promotions[1].averageUnitPrice,59);assert.equal(cotton.periods['2026-10-1'],undefined);
const cedar=byBarcode('4710660888530');assert.equal(cedar.productId,'');assert.equal(nov(cedar).matchMethod,'BARCODE');assert.equal(nov(cedar).promotions[0].averageUnitPrice,99);assert.equal(nov(cedar).promotions[0].optional,true);assert.equal(additions[0].cost,undefined);
assert.equal(nov(byBarcode('4710660886567')).promotions[1].promotionPrice,238);assert.equal(nov(byBarcode('4710660886567')).promotions[1].averageUnitPrice,119);
assert.equal(nov(byBarcode('4710660886574')).promotions[0].promotionPrice,298);assert.equal(nov(byBarcode('4710660886574')).promotions[0].averageUnitPrice,149);
assert.equal(nov(byBarcode('4710660883436')).promotions[1].promotionPrice,111);assert.equal(nov(byBarcode('4710660883436')).promotions[1].averageUnitPrice,55.5);
const absent=byBarcode('4710660888127');assert.ok(absent.periods['2026-10-2']);assert.equal(absent.periods['2026-11-1'],undefined);
for(const [date,current,next] of [['2026-10-20','10-2','11-1'],['2026-11-01','11-1','11-2'],['2026-11-21','11-2',undefined],['2026-12-03','11-2',undefined]]){const ctx=core.context(data,date);assert.equal(ctx.current?.label,current);assert.equal(ctx.next?.label,next);}
const repeat=importRows({rows:report.rawRows,issues:[]},all,data);assert.equal(repeat.report.added,0);assert.equal(repeat.report.skipped,108);assert.equal(repeat.report.errorCount,0);assert.deepEqual(repeat.data.products,data.products);
const oldMaster=vm.runInNewContext(execFileSync('git',['show','c758b45:index.html'],{encoding:'utf8'}).match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1]);assert.equal(JSON.stringify(master.map(p=>[p.name,p.code,p.cost])),JSON.stringify(oldMaster.map(p=>[p.name,p.code,p.cost])));
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html');if(!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(process.env.PX_LIVE||`http://127.0.0.1:${server.address().port}/index.html`,{waitUntil:'networkidle'});await page.locator('[data-tab="campaign"]').click();
await page.evaluate(()=>{PXPromo.today=()=> '2026-11-01';renderCampaignSearch()});const results=[];
for(const [query,expected] of [['天然棉紗布','均價 $59'],['挪威雪松','均價 $99'],['4710660888530','均價 $99'],['65010647','均價 $119'],['4710660886574','均價 $149'],['4710660883436','均價 $55.5']]){await page.locator('#campaignSearch').fill(query);const text=await campaignText(page);assert.ok(text.includes(expected));assert.ok(text.includes('本檔 11-1'));results.push({query,result:text});assert.equal(await page.locator('.campaign-result').count(),1);}
await page.locator('#campaignSearch').fill('4710660888127');assert.match(await campaignText(page),/本檔未提供促銷價格/);await page.locator('#campaignFilter').selectOption('all');assert.match(await campaignText(page),/10-2/);
for(const [date,label] of [['2026-10-20','10-2'],['2026-11-01','11-1'],['2026-11-21','11-2']]){await page.evaluate(date=>{PXPromo.today=()=>date;renderCampaignSearch()},date);await page.locator('#campaignFilter').selectOption('current');await page.locator('#campaignSearch').fill('65010647');assert.ok((await campaignText(page)).includes('本檔 '+label));}
await page.locator('#campaignFilter').selectOption('all');const history=await campaignText(page);for(const label of ['10-1','10-2','11-1','11-2'])assert.ok(history.includes(label));
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{PXPromo.today=()=> '2026-11-01';renderCampaignSearch()});await page.locator('#campaignFilter').selectOption('current');await page.locator('#campaignSearch').fill('挪威雪松');if(!process.env.PX_LIVE)await page.screenshot({path:path.join(root,'tests/november-mobile.png'),fullPage:true});
let overflow=0;for(const width of [320,360,375,390,393,430,768,1280]){await page.setViewportSize({width,height:844});overflow=Math.max(overflow,await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth));}assert.equal(overflow,0);assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',novemberTests:20,totalPeriods:214,overflow,consoleErrors:errors,results},null,2));await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
