const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),config=require('../product-catalog.json'),search=require('../product-search-core').create(config),comparison=require('../competitor-comparison-core'),records=require('../competitor-prices.json');
const master=[...vm.runInNewContext(html.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1]),...require('../px-product-additions.json')];
assert.equal(config.products.length,55);assert.equal(records.length,29);assert.equal(new Set(config.products.map(p=>p.id)).size,55);
for(const p of master){assert.ok(search.searchOwn(master,p.code||p.barcode).some(r=>r.name===p.name));assert.ok(search.searchOwn(master,p.name).some(r=>r.name===p.name));}
for(const [q,n] of [['夾鏈袋',6],['烘焙紙',2],['洗碗精',3],['OP 1公斤',3],['茶酚 800公克',1],['拖地巾',3],['ＯＰ保鮮膜',2],['沒有這個商品',0]])assert.equal(search.searchOwn(master,q).length,n,q);
assert.deepEqual(search.searchMarket(records,'妙潔 30公分 55公尺').map(p=>p.retailerProductId),['3142300100101']);
assert.deepEqual(search.searchMarket(records,'妙洁 ３０ＣＭ ５５Ｍ').map(p=>p.retailerProductId),['3142300100101']);
assert.equal(search.searchMarket(records,'鋁箔').length,8);assert.equal(search.searchMarket(records,'烘焙紙').length,7);
assert.ok(!search.searchMarket(records,'5公尺').some(p=>p.lengthM===55),'5m must not match 55m');
for(const p of records)assert.ok(search.searchMarket(records,p.retailerProductId).some(r=>r.competitorProductId===p.competitorProductId));
const foil=records.find(p=>p.retailerProductId==='3142002400101');assert.equal(foil.lengthM,8);assert.equal(foil.widthCm,null);
assert.ok(records.filter(p=>p.brand==='OP'&&p.category==='CLING_FILM').every(p=>comparison.getCompetitorMetrics(p).totalLengthM===null));
assert.ok(!records.some(p=>p.retailerProductId==='3142400200101'),'ambiguous bonus length excluded');
console.log('PASS catalog IDs, own aliases/specs, public categories and unknown dimensions');
if(process.argv.includes('--unit'))process.exit(0);
const {chromium}=require('C:/Users/林弘昇/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html');if(!fs.existsSync(f)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const page=await browser.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('uni-prosperity'))requests.push(r.url())});await page.goto(process.env.PX_LIVE||`http://127.0.0.1:${server.address().port}/index.html`,{waitUntil:'networkidle'});await page.locator('[data-tab="campaign"]').click();
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});await page.locator('#campaignBrowseAll').click();assert.equal(await page.locator('.public-catalog-list>li').count(),29);assert.equal(await page.locator('#campaignSearch').inputValue(),'');assert.deepEqual(await page.locator('.public-catalog-list>li').evaluateAll(es=>es.map(e=>e.value)),Array.from({length:29},(_,i)=>i+1));assert.equal(await page.locator('#competitorResults .competitor-benchmark').count(),0);for(const [category,count] of [['CLING_FILM',14],['FOIL',8],['BAKING_PAPER',7]]){await page.locator('[data-catalog-category="'+category+'"]').click();assert.equal(await page.locator('.public-catalog-list>li').count(),count);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);}await page.locator('[data-catalog-category="ALL"]').click();const item=page.locator('.public-catalog-list>li').first();await item.locator(':scope > details > summary').click();assert.equal(await item.locator(':scope > details[open]').count(),1);await item.locator('.competitor-details > summary').click();assert.match(await item.innerText(),/最後成功更新/);await page.locator('[data-catalog-close]').click();assert.equal(await page.locator('.public-catalog-list>li').count(),0);}
 const checks=[];for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const q of ['夾鏈袋','烘焙紙','洗碗精','茶酚 800公克','妙潔 30公分 55公尺','南亞','ＯＰ保鮮膜','OP 330尺','鋁箔']){await page.locator('#campaignSearch').fill(q);const own=search.searchOwn(master,q),market=search.searchMarket(records,q,own);assert.equal(await page.locator('#campaignResults .campaign-result').count(),own.length,q);assert.equal(await page.locator('#competitorResults .competitor-card').count(),market.length,q);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);checks.push({width,query:q,status:'PASS'});}}
 await page.locator('#campaignSearch').fill('鋁箔');assert.equal(await page.locator('#competitorResults .competitor-benchmark').count(),0);await page.locator('[data-px-compare="65010209"]').click();assert.equal(await page.locator('#competitorResults .competitor-benchmark').count(),1);assert.equal(await page.locator('#competitorResults [data-lookup-direction="UNAVAILABLE"]').count(),8);assert.match(await page.locator('#competitorResults').innerText(),/規格資料不足|規格尚未確認|無法公平換算/);
 await page.locator('#campaignSearch').fill('妙潔 30公分 55公尺');await page.locator('#competitorResults summary').click();assert.match(await page.locator('#competitorResults').innerText(),/最後成功更新/);assert.match(await page.locator('#competitorResults').innerText(),/來源規格/);assert.equal(await page.locator('#competitorResults a.competitor-source-link').count(),1);
 await page.locator('#campaignSearch').fill('OP 330尺');assert.equal(await page.locator('#competitorResults .competitor-card').count(),1);assert.match(await page.locator('#competitorResults').innerText(),/自家公開價/);assert.equal(await page.locator('#competitorResults .competitor-benchmark').count(),0);
 await page.locator('#campaignSearch').fill('');assert.equal(await page.locator('#competitorResults .competitor-card').count(),0);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 await page.locator('#campaignSearch').fill('烘焙紙');if(process.env.PX_SCREENSHOTS){await page.locator('#campaignBrowseAll').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(process.env.PX_SCREENSHOTS,'public-products-mobile.png')});await page.setViewportSize({width:1440,height:900});await page.screenshot({path:path.join(process.env.PX_SCREENSHOTS,'public-products-desktop.png')});}
 console.log(JSON.stringify({status:'PASS',checks,consoleErrors:errors,retailerFrontendRequests:requests,ownProducts:master.length,publicProducts:records.length},null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});


