'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const {chromium}=require('C:/Users/林弘昇/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),base='43d2a523f180c362c16bd100b79af88d90c2310c',read=f=>fs.readFileSync(path.join(root,f)),old=f=>execFileSync('git',['show',base+':'+f],{cwd:root}),mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.json':'application/json'};
const server=http.createServer((req,res)=>{const file=decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1)||'index.html';if(file==='favicon.ico'){res.writeHead(204).end();return}try{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(read(file));}catch(e){res.writeHead(404).end();}});
const tabs=[['calc','c',['cPrice','cCost','cFee'],'cMargin','cRows'],['reverse','r',['rTarget','rCost','rFee'],'rPrice','rRows'],['scenario','s',['sPriceA','sPrice','sPriceC','sCost','sFee'],'scenarioSummaryRows','scenarioResults'],['promo','p',['pA','pCost','pFee'],'pMargin','pRows']];
async function setCase(page,tab){const [name,p]=tab;await page.locator(`[data-tab="${name}"]`).click();await page.locator('#'+p+'Product').fill('65010209');if(p==='c')await page.locator('#cPrice').fill('123.45');if(p==='r')await page.locator('#rTarget').fill('35');if(p==='s')for(const [id,v]of [['sPriceA','49'],['sPrice','59'],['sPriceC','75']])await page.locator('#'+id).fill(v);if(p==='p')await page.locator('#pA').fill('99');}
async function result(page,tab){const [,p,ids,hero,rows]=tab;return page.evaluate(({ids,hero,rows,p})=>({inputs:ids.map(id=>document.getElementById(id).value),hero:document.getElementById(hero).textContent,rows:document.getElementById(rows).innerHTML,front:document.getElementById(p+'Px').textContent,decision:p==='s'?document.getElementById('decisionSummary').textContent:null}),{ids,hero,rows,p});}
async function independentResults(page){return page.evaluate(()=>{
 const product=PX_Q3_PRODUCTS.find(p=>p.code==='65010209'),source=PX_SALES[product.name],benchmark=competitorBenchmark(product);
 return {sales:PX_SALES_DASHBOARD_CORE.analyze(PX_PERIODS,source.sales),competitors:COMPETITOR_DATA.records.map(record=>CompetitorComparison.comparePxToCompetitor(benchmark,record))};
});}
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const local='http://127.0.0.1:'+server.address().port+'/index.html',url=process.env.PX_LIVE||local;
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const bc=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),baseline=await bc.newPage();await baseline.route('**/index.html*',r=>r.fulfill({contentType:mime['.html'],body:old('index.html')}));await baseline.route('**/px-rsp-data.js*',r=>r.fulfill({contentType:mime['.js'],body:old('px-rsp-data.js')}));await baseline.goto(local,{waitUntil:'networkidle'});
 const before={};for(const tab of tabs){await setCase(baseline,tab);before[tab[0]]=await result(baseline,tab);}const independentBefore=await independentResults(baseline);await bc.close();
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[],screenshots=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(url,{waitUntil:'networkidle'});
 const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
 const html=await(await context.request.get(url)).text();assert.equal(html.replace(/\r\n/g,'\n'),read('index.html').toString().replace(/\r\n/g,'\n'),'HTTP HTML matches local release');
 for(const file of ['px-rsp-data.js?v=4.1.18-rsp-confirmed','px-promo-ui.js','px-sales-data.js','service-worker.js?v=4.1.18-rsp-confirmed']){const response=await context.request.get(new URL(file,url).href);assert.equal(response.status(),200);assert.equal(hash((await response.text()).replace(/\r\n/g,'\n')),hash(read(file.split('?')[0]).toString().replace(/\r\n/g,'\n')),file+' HTTP matches release');}
 const master=require('../scripts/sales-data-io.cjs').readMaster(),values=require('../PX_RSP_MAPPING_AUDIT.json').records;
 assert.deepEqual(await independentResults(page),independentBefore,'sales and competitor formulas unchanged after three RSP values updated');
 const canonical=await page.evaluate(()=>({...PX_RSP_DATA}));
 for(const mutation of [null,0,999999999]){
  await page.evaluate(value=>{window.PX_RSP_DATA=Object.freeze(Object.fromEntries(Object.keys(PX_RSP_DATA).map(name=>[name,value])));},mutation);
  for(const tab of tabs){await setCase(page,tab);assert.deepEqual(await result(page,tab),before[tab[0]],tab[0]+' remains identical when RSP is '+mutation);}
  assert.deepEqual(await independentResults(page),independentBefore,'sales and competitor results do not read mutated RSP');
 }
 await page.evaluate(values=>{window.PX_RSP_DATA=Object.freeze(values);},canonical);
 for(const tab of tabs){const [name,p]=tab;await setCase(page,tab);assert.deepEqual(await result(page,tab),before[name],name+' all inputs and results unchanged');assert.equal(await page.locator('#'+p+'ProductInfo .px-rsp b').innerText(),'$110');
  for(const product of master){if(!Number.isFinite(product.cost)){assert.match(await page.evaluate(({p,product})=>productInfoMarkup(productBindings.find(b=>b.productId===p+'Product'),product,null),{p,product}),/class="px-metric px-rsp"><span>RSP<\/span><b>\$359<\/b>/);continue;}const priceIds=tab[2].filter(id=>!id.endsWith('Cost')),prior=await Promise.all(priceIds.map(id=>page.locator('#'+id).inputValue()));await page.locator('#'+p+'Product').fill(product.name);const r=values.find(r=>r.productName===product.name),display=r.rsp===null?'—':'$'+r.rsp;assert.equal(await page.locator('#'+p+'ProductInfo .px-rsp b').innerText(),display,name+' '+product.name);assert.deepEqual(await Promise.all(priceIds.map(id=>page.locator('#'+id).inputValue())),prior,'RSP never autofills price/fee/target');}
  const examples={c:['OP生物抗菌密封袋M(PX)','$83'],r:['OP生物抗菌密封袋L(PX)','$83'],s:['OP生物分解抗菌立體密封袋S','$179'],p:['香氛豆-粉紅甜蜜果香淡香水','—']};
  await page.locator('#'+p+'Product').fill(examples[p][0]);assert.equal(await page.locator('#'+p+'ProductInfo .px-rsp b').innerText(),examples[p][1]);
  for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>Math.max(0,document.documentElement.scrollWidth-innerWidth)),0);const grid=page.locator('#'+p+'ProductInfo .px-info-grid'),cells=await grid.locator('.px-metric').evaluateAll(es=>es.map(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width}}));assert.ok(cells.every(c=>Math.abs(c.w-cells[0].w)<1));if(width===390)assert.equal(new Set(cells.map(c=>Math.round(c.x))).size,2);if(width===1280){const rows=cells.reduce((a,c)=>{const k=Math.round(c.y);a[k]=(a[k]||0)+1;return a},{});assert.ok(!Object.values(rows).includes(1),'no lonely desktop RSP');}if(width===390||width===1280){await grid.scrollIntoViewIfNeeded();const file=path.join(os.tmpdir(),`px-rsp-${process.env.PX_LIVE?'production':'local'}-${name}-${width}.png`);await page.screenshot({path:file});screenshots.push(file);}}
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>navigator.serviceWorker.ready);const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await page.reload({waitUntil:'networkidle'});await page.locator('#cProduct').fill('65010209');assert.equal(await page.locator('#cProductInfo .px-rsp b').innerText(),'$110');assert.deepEqual(await page.evaluate(()=>caches.keys()),['px-workbench-v4.1.18-rsp-confirmed']);
 assert.ok(await page.evaluate(async()=>!!await(await caches.open('px-workbench-v4.1.18-rsp-confirmed')).match(new URL('px-rsp-data.js?v=4.1.18-rsp-confirmed',location.href))));await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await page.locator('#cProduct').fill('OP天然棉紗布(3片入)');assert.equal(await page.locator('#cProductInfo .px-rsp b').innerText(),'$99');assert.deepEqual(errors,[]);
 console.log(JSON.stringify({status:'PASS',mode:process.env.PX_LIVE?'PRODUCTION':'LOCAL',productsAcrossFourTabs:220,inputsAndResultsParity:'PASS',priceAutofill:'NONE',layout:'320/390/768/1280 PASS',overflow:0,consoleErrors:0,httpCoherence:'PASS',hardReload:'PASS',offline:'PASS',screenshots},null,2));
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
