const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),http=require('node:http'),os=require('node:os'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),base='ed305aa184b8bfd980c1234315cb56e2e6a45104',core=require('../px-sales-radar-core'),explorer=require('../px-sales-explorer-core');
for(const file of ['px-sales-data.js','px-sales-analysis.js','same-period-sales.js','px-sales-explorer-core.js','px-sales-dashboard-core.js','px-sales-dashboard.css','px-sales-multi-view.js','px-sales-multi.css','px-promo-core.js','px-promo-ui.js','px-promo-prices.js','px-promo-prices.json','px-replacement-data.js','new-product-calculator.js','new-product-organizer.js','scenario-summary.js','decision-summary.js','product-catalog.js','assets/brand/px-logo.svg','assets/brand/px-icon.svg'])assert.equal(fs.readFileSync(path.join(root,file),'utf8').replace(/\r\n/g,'\n'),execFileSync('git',['show',base+':'+file],{encoding:'utf8'}).replace(/\r\n/g,'\n'),file+' unchanged');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),inline=s=>[...s.replace(/\r\n/g,'\n').matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n').replace(/service-worker\.js\?v=[^"']+/g,'service-worker.js?VERSION');assert.equal(inline(html),inline(execFileSync('git',['show',base+':index.html'],{encoding:'utf8'})),'all margin logic/master unchanged');
const products=[...vm.runInNewContext(html.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1]),...require('../px-product-additions.json')];assert.ok(products.every(p=>!('category'in p)&&!('brand'in p)&&!('type'in p)),'no inferred master categories');global.window={};require('../px-sales-data');
const real=core.create(window.PX_SALES_PERIODS,window.PX_SALES_DATA,products),realResult=real.analyze(explorer.preset('2026/08','ytd'));assert.deepEqual(realResult.counts,{total:53,complete:37,growing:22,declining:15,flat:0,insufficient:16,high:4,excluded:2});
for(const row of realResult.rows)assert.deepEqual(row.comparison,explorer.compareRanges(window.PX_SALES_PERIODS,window.PX_SALES_DATA[row.name].sales,realResult.ranges),'same released calculation');
const months=Array.from({length:24},(_,i)=>explorer.shift('2025/01',i)),series=(a,b)=>months.map((_,i)=>i<12?a:b),data={high:{sales:series(10,12)},small:{sales:series(10,11)},flat:{sales:series(10,10)},decline:{sales:series(10,9)},severe:{sales:series(10,8)},tie:{sales:series(20,16)},zero:{sales:series(0,10)},partial:{sales:series(10,30)},noPrior:{sales:series(null,10)},earlier:{sales:series(10,12)},trueZero:{sales:series(10,0)},none:{sales:series(null,null)}};data.partial.sales[15]=null;data.earlier.sales[23]=null;
const fixtureProducts=Object.keys(data).map((name,i)=>({name,barcode:'47100000000'+i,code:String(65010000+i)})),fixture=core.create(months,data,fixtureProducts),snapshot=JSON.stringify(data),result=fixture.analyze(explorer.preset('2026/12','ytd'));
assert.equal(result.counts.total,11);assert.equal(result.counts.complete,7);assert.equal(result.counts.growing,2);assert.equal(result.counts.declining,4);assert.equal(result.counts.flat,1);assert.equal(result.counts.insufficient,4);assert.deepEqual(result.attention.map(r=>r.name),['trueZero','tie','severe','decline']);assert.deepEqual(result.growth.map(r=>r.name),['high','small']);assert.deepEqual(result.decline.map(r=>r.name),['trueZero','tie','severe','decline']);assert.ok(!result.growth.some(r=>r.name==='partial'||r.name==='zero'));
assert.equal(result.rows.find(r=>r.name==='earlier').latest.latestMonth,'2026/11');assert.equal(result.rows.find(r=>r.name==='zero').comparison.rate.status,'zero-baseline');assert.equal(result.rows.find(r=>r.name==='trueZero').comparison.a.total,0);assert.equal(result.rows.find(r=>r.name==='partial').comparison.a.count,11);assert.equal(result.rows.find(r=>r.name==='noPrior').comparison.b.total,null);
for(const [name,label] of [['high','高成長'],['small','成長'],['flat','穩定'],['decline','衰退'],['severe','明顯衰退'],['zero','資料不足'],['partial','資料不足']])assert.equal(result.rows.find(r=>r.name===name).status.label,label);
assert.deepEqual(fixture.query(result,{search:fixtureProducts[0].barcode}).map(r=>r.name),['high']);assert.deepEqual(fixture.query(result,{search:fixtureProducts[1].code}).map(r=>r.name),['small']);assert.equal(fixture.query(result,{status:'持平'}).length,1);
for(let i=0;i<250;i++){fixture.query(result,{search:i%2?'high':'',status:'all',sort:['total','growth','difference','name'][i%4]});assert.equal(fixture.analyze(result.ranges),result)}assert.deepEqual(fixture.diagnostics(),{calculations:1,cachedPeriods:1,searchIndexBuilds:1,sourceBuilds:1,covered:11});assert.equal(JSON.stringify(data),snapshot);
for(const preset of ['three','six'])assert.equal(fixture.analyze(explorer.preset('2026/12',preset)).ranges.aStart,preset==='three'?'2026/10':'2026/07');assert.equal(fixture.analyze({...result.ranges,aStart:'2027/01'}).error,'起始月份不可晚於結束月份');assert.doesNotMatch(result.summary.join(' '),/缺貨|促銷不足|價格影響|陳列問題|預測|熱銷/);
console.log('PASS radar unit: 53 coverage, exact released comparisons, thresholds, ties, null/zero, own latest, cached filtering, immutable data');if(process.argv.includes('--unit'))process.exit(0);
const {chromium}=require('C:/Users/林弘昇/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1)||'index.html');if(!fs.existsSync(file)){res.writeHead(404).end();return}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write'],hasTouch:true}),page=await context.newPage(),errors=[],screenshots=[],url=process.env.PX_LIVE||'http://127.0.0.1:'+server.address().port+'/index.html';page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(url,{waitUntil:'networkidle'});
 const card=page.locator('#cSalesPerformance .sales2'),pane=card.locator('.sales23-radar-pane');assert.equal(await card.locator('[data-sales-mode="single"]').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>PX_SALES_RADAR.diagnostics().calculations),0,'lazy radar');await card.locator('[data-sales-mode="single"]').focus();await page.keyboard.press('End');assert.equal(await pane.isVisible(),true);
 assert.deepEqual(await pane.locator('.sales23-kpis strong').allTextContents(),['53 支','37 支','22 支','15 支']);assert.equal(await pane.locator('tbody tr').count(),53);assert.equal(await pane.locator('.sales23-attention-item').count(),5);assert.equal(await pane.locator('.sales23-growth article').count(),5);assert.equal(await pane.locator('.sales23-volume article').count(),10);
 const attention=realResult.attention.map(r=>r.name);assert.deepEqual(await pane.locator('.sales23-attention-item').evaluateAll(nodes=>nodes.map(e=>e.dataset.radarProduct)),attention.slice(0,5));await pane.locator('[data-radar-expand]').click();assert.equal(await pane.locator('.sales23-attention-item').count(),15);await pane.locator('[data-radar-expand]').click();assert.equal(await pane.locator('.sales23-attention-item').count(),5);
 const searches=['鋁箔','65010209','4710660884433','ＯＰ 無雙酚Ａ鋁箔８００公分－１２入'];for(const q of searches){await pane.locator('.sales23-search').fill(q);assert.ok(await pane.locator('tbody tr').count()>0)}assert.equal(await pane.locator('tbody tr').count(),1);await pane.locator('.sales23-search').fill('');
 for(const label of ['高成長','成長','持平','衰退','明顯衰退','資料不足']){await pane.locator('[data-radar-status="'+label+'"]').click();assert.equal(await pane.locator('tbody tr').count(),real.query(realResult,{status:label}).length)}await pane.locator('[data-radar-status="all"]').click();
 for(const sort of ['total','growth','difference','name']){await pane.locator('.sales23-sort').selectOption(sort);assert.deepEqual(await pane.locator('tbody tr').evaluateAll(nodes=>nodes.map(n=>n.dataset.radarProduct)),real.query(realResult,{sort}).map(r=>r.name))}assert.equal(await page.evaluate(()=>PX_SALES_RADAR.diagnostics().calculations),1,'search/status/sort/expand never recalculate');
 for(const preset of ['three','six','ytd']){await pane.locator('[data-radar-preset="'+preset+'"]').click();assert.deepEqual(await pane.locator('.sales23-kpis strong').allTextContents(),Object.entries(real.analyze(explorer.preset('2026/08',preset)).counts).slice(0,4).map(([,v])=>v+' 支'))}assert.equal(await page.evaluate(()=>PX_SALES_RADAR.diagnostics().calculations),3);
 await pane.locator('[data-radar-preset="three"]').click();const product='OP無雙酚A鋁箔800公分-12入';await pane.locator('.sales23-search').fill('65010209');await pane.locator('tbody .sales23-name[data-radar-open]').click();await card.locator('.sales2-total').waitFor({state:'visible'});assert.equal(await card.locator('[data-sales-mode="single"]').getAttribute('aria-pressed'),'true');assert.equal(await card.locator('.sales2-start').inputValue(),'2026-06');assert.equal(await card.locator('.sales2-end').inputValue(),'2026-08');assert.equal(await card.locator('.sales2-total').innerText(),'26,951');assert.equal(await page.locator('#cProduct').inputValue(),product);
 await card.locator('[data-sales-mode="radar"]').click();await pane.locator('.sales23-search').fill('');const namesToAdd=['OP無雙酚A鋁箔1500公分-12入','OP抗菌木漿棉','OP細柔無砂海綿菜瓜布','OP生物分解抗菌密封袋XL'];for(const name of namesToAdd)await pane.locator('tbody tr[data-radar-product="'+name+'"] [data-radar-add]').click();assert.equal(await pane.isVisible(),true);await pane.locator('tbody tr[data-radar-product="'+product+'"] [data-radar-add]').click();assert.match(await pane.locator('.sales23-feedback').innerText(),/已在/);await pane.locator('tbody tr[data-radar-product="OP專科防臭袋S"] [data-radar-add]').click();assert.match(await pane.locator('.sales23-feedback').innerText(),/選滿 5/);await card.locator('[data-sales-mode="multi"]').click();assert.match(await card.locator('.sales-selection-status').innerText(),/已選 5/);await card.locator('[data-sales-mode="radar"]').click();
 await pane.locator('[data-radar-preset="custom"]').click();await pane.locator('[data-radar-range="bStart"]').fill('2025-01');await pane.locator('[data-radar-range="bEnd"]').fill('2025-03');assert.match(await pane.locator('.sales-warning').innerText(),/並非 YoY/);await pane.locator('.sales23-search').fill('65010209');await pane.locator('tbody .sales23-name[data-radar-open]').click();assert.equal(await card.locator('.sales2-start').inputValue(),'2026-06');assert.match(await card.locator('.sales23-handoff-note').innerText(),/固定比較去年同月/);await card.locator('.sales2-advanced>summary').click();await card.locator('.sales-custom>summary').click();assert.equal(await card.locator('.sales-custom [data-range="bStart"]').inputValue(),'2025-01');assert.equal(await card.locator('.sales-custom [data-range="bEnd"]').inputValue(),'2025-03');await card.locator('.sales2-advanced>summary').click();await card.locator('[data-sales-mode="radar"]').click();await pane.locator('[data-radar-prior]').click();assert.equal(await pane.locator('[data-radar-range="bStart"]').inputValue(),'2025-06');await pane.locator('[data-radar-range="aStart"]').fill('2026-09');assert.match(await pane.locator('.sales-error').innerText(),/起始月份/);assert.equal(await pane.locator('tbody tr').count(),0);await pane.locator('[data-radar-preset="ytd"]').click();await pane.locator('.sales23-search').fill('');
 const performance=await page.evaluate(()=>{const start=performance.now(),counts=PX_SALES_RADAR.diagnostics();return{counts,start}});assert.ok(performance.counts.calculations<15);
 for(const [width,height] of [[320,568],[360,800],[375,667],[390,844],[393,852],[430,932],[768,1024],[820,1180],[1024,768],[1280,900],[1366,768],[1440,900],[1920,1080],[844,390]]){await page.setViewportSize({width,height});assert.equal(await page.evaluate(()=>Math.max(0,document.documentElement.scrollWidth-innerWidth)),0);assert.equal(await pane.locator('.sales23-kpis').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),width<=800?2:4);if(width===390||width===1280){const file=path.join(os.tmpdir(),'px-sales23-'+(process.env.PX_LIVE?'production':'local')+'-'+width+'.png');await card.screenshot({path:file});screenshots.push(file);await pane.evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-12));const viewportFile=file.replace('.png','-viewport.png');await page.screenshot({path:viewportFile});screenshots.push(viewportFile)}}
 await page.reload({waitUntil:'networkidle'});assert.equal(await card.locator('[data-sales-mode="single"]').getAttribute('aria-pressed'),'true');await page.evaluate(()=>navigator.serviceWorker.ready);assert.deepEqual(await page.evaluate(()=>caches.keys()),['px-workbench-v4.1.16-sales24']);
 // Synthetic boundary data is injected only into an isolated browser; no source file is changed.
 const fixtureContext=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),fp=await fixtureContext.newPage();fp.on('pageerror',e=>errors.push(e.message));const fNames=products.slice(0,11).map(p=>p.name),values=Object.values(data).slice(0,11).map(p=>p.sales);await fp.route('**/px-sales-data.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text())+'\nwindow.PX_SALES_PERIODS='+JSON.stringify(months)+';window.PX_SALES_DATA={'+fNames.map((name,i)=>JSON.stringify(name)+':{sales:'+JSON.stringify(values[i])+'}').join(',')+'};'})});await fp.goto(url,{waitUntil:'networkidle'});const fc=fp.locator('#cSalesPerformance .sales2');await fc.locator('[data-sales-mode="radar"]').click();const rp=fc.locator('.sales23-radar-pane');assert.deepEqual(await rp.locator('.sales23-kpis strong').allTextContents(),['11 支','7 支','2 支','4 支']);assert.equal(await rp.locator('.sales23-growth article').count(),2);assert.equal(await rp.locator('.sales23-decline article').count(),4);await rp.locator('.sales23-search').fill(fNames[6]);assert.match(await rp.locator('tbody tr').innerText(),/基準為 0/);await rp.locator('.sales23-search').fill(fNames[7]);assert.match(await rp.locator('tbody tr').innerText(),/部分月份資料不足/);await rp.locator('.sales23-search').fill(fNames[9]);assert.match(await rp.locator('tbody tr').innerText(),/2026\/11/);await rp.locator('.sales23-search').fill(fNames[10]);assert.match(await rp.locator('tbody tr').innerText(),/0 支/);assert.doesNotMatch(await rp.innerText(),/Infinity|NaN/);assert.equal(await fp.evaluate(()=>Math.max(0,document.documentElement.scrollWidth-innerWidth)),0);await fixtureContext.close();assert.deepEqual(errors,[]);
 console.log(JSON.stringify({status:'PASS',mode:process.env.PX_LIVE?'PRODUCTION':'LOCAL',cases:25,coverage:realResult.counts,modes:'PASS',periods:'PASS',rankings:'PASS',partialZeroLatest:'PASS',searchFilterSort:'PASS',singleHandoff:'PASS',multiHandoff:'PASS',keyboard:'PASS',performance:performance.counts,viewports:14,overflow:0,consoleErrors:errors,screenshots},null,2));
 }finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
