const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os');
const {execFileSync}=require('node:child_process');
const {chromium}=require('C:/Users/林弘昇/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const core=require('../px-sales-explorer-core.js'),phase1=require('../px-sales-analysis.js');
const root=path.resolve(__dirname,'..'),base='371bc2ff768381fd4137084d9b5a2834711bdce6';
const read=file=>fs.readFileSync(path.join(root,file),'utf8').replace(/\r\n/g,'\n');
const baseline=file=>execFileSync('git',['show',`${base}:${file}`],{encoding:'utf8'}).replace(/\r\n/g,'\n');
for(const file of ['px-sales-data.js','px-product-additions.js','px-replacement-data.js','px-promo-core.js','px-promo-prices.js','px-sales-analysis.js','same-period-sales.js'])assert.equal(read(file),baseline(file),`${file} unchanged`);
const inline=html=>[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(match=>match[1]).join('\n').replace(/service-worker\.js\?v=[^"']+/g,'service-worker.js?RELEASE');
assert.equal(inline(read('index.html')),inline(baseline('index.html')),'existing inline formulas, product master, and logic unchanged');
const periods=Array.from({length:24},(_,i)=>core.shift('2025/01',i));
const sales=Array.from({length:24},(_,i)=>i<12?10:20);
const ytd=core.preset('2026/08','ytd'),comparison=core.compareRanges(periods,sales,ytd);
assert.equal(comparison.a.total,160);assert.equal(comparison.b.total,80);assert.equal(comparison.difference,80);assert.equal(comparison.rate.value,100);assert.equal(comparison.samePeriod,true);assert.equal(comparison.a.average,20);
const unequal=core.compareRanges(periods,sales,{...ytd,bEnd:'2025/06'});assert.equal(unequal.unequal,true);assert.equal(unequal.rateLabel,'期間差異（非同期）');assert.ok(unequal.warnings.includes('比較期間長度不同'));
const gaps=sales.slice();gaps[13]=null;gaps[14]=0;gaps[19]=null;
const partial=core.compareRanges(periods,gaps,ytd);assert.equal(partial.a.count,6);assert.equal(partial.a.length,8);assert.equal(partial.a.total,100);assert.equal(partial.partial,true);assert.match(partial.rateLabel,/非完整/);
assert.equal(core.compareRanges(['2025/01','2026/01'],[0,5],core.preset('2026/01','ytd')).rate.status,'zero-baseline');
assert.match(core.range(periods,sales,'2026/08','2026/01').error,/起始月份/);assert.ok(core.range(periods,sales,'','2026/01').error);
assert.equal(core.range(periods,sales,'2024/01','2024/08').total,null);
assert.deepEqual(core.preset('2026/08','three'),{aStart:'2026/06',aEnd:'2026/08',bStart:'2025/06',bEnd:'2025/08'});
assert.equal(core.preset('2026/02','six').bStart,'2024/09');assert.equal(core.shift('2026/03',-12),'2025/03');
const details=core.monthDetails(['2025/02','2026/01','2026/02','2026/03'],[10,20,null,0]);
assert.equal(details[0].mom.status,'insufficient');assert.equal(details[1].value,null);assert.equal(details[0].value,0);
const zeroBase=core.monthDetails(['2025/02','2026/01','2026/02'],[0,0,20])[0];assert.equal(zeroBase.mom.status,'zero-baseline');assert.equal(zeroBase.yoy.status,'zero-baseline');
const ext=core.extrema(periods,sales);assert.equal(ext.complete12,true);assert.equal(ext.highMonths.length,12);assert.equal(ext.lowMonths.length,12);
const short=core.extrema(periods,Array(22).fill(null).concat([0,5]));assert.equal(short.complete12,false);assert.equal(short.low,0);assert.deepEqual(short.lowMonths,['2026/11']);assert.equal(short.count,2);
const broken12=sales.slice();broken12[18]=null;assert.equal(core.extrema(periods,broken12).complete12,false);assert.equal(core.extrema(periods,broken12).count,23);
assert.equal(core.extrema(periods,Array(24).fill(null)).high,null);
assert.equal(core.yearly(periods,gaps)[0].values[1],null);assert.equal(core.yearly(periods,gaps)[0].values[2],0);
const synthetic={a:{sales},b:{sales:sales.map(v=>v*2)},c:{sales:Array(23).fill(null).concat(30)},d:{sales:Array(24).fill(null)},e:{sales:sales.map(()=>0)}};
assert.equal(core.multi(periods,synthetic,['a','b'],ytd)[0].name,'b');assert.equal(core.multi(periods,synthetic,['a','b','c','d','e'],ytd).length,5);assert.equal(core.multi(periods,synthetic,['a','a'],ytd).length,1);assert.equal(core.multi(periods,synthetic,['a','b','d'],ytd,'difference')[0].name,'b');assert.equal(core.multi(periods,synthetic,['a','e','d'],ytd,'growth')[0].name,'a');
assert.doesNotMatch(read('px-sales-explorer.js'),/熱銷|滯銷|推薦商品|最佳商品|最差商品|未來會|促銷成功/);
global.window={};require('../px-sales-data.js');const source=window.PX_SALES_DATA,months=window.PX_SALES_PERIODS,foil='OP無雙酚A鋁箔800公分-12入';
const real=core.compareRanges(months,source[foil].sales,ytd);assert.equal(real.a.total,74431);assert.equal(real.b.total,65240);assert.equal(real.difference,9191);
// Presentation checks moved to sales-dashboard.cjs; original calculation fixtures stay intact.
console.log('PASS sales-phase2.cjs original data/formula/edge-case calculations');
