const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{execFileSync}=require('node:child_process');
const {chromium}=require('C:/Users/林弘昇/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),current=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/\r\n/g,'\n'),base=execFileSync('git',['show','HEAD:index.html'],{encoding:'utf8'}).replace(/\r\n/g,'\n');
for(const [from,to] of [['function model(','function rows('],['function calcC(','function calcR(']])assert.equal(current.slice(current.indexOf(from),current.indexOf(to)),base.slice(base.indexOf(from),base.indexOf(to)),from+' core unchanged');
const promoCore='const t=$("promoType").value,cost=n("pCost"),px=pct(n("pPx")),fee=pct(n("pFee")),a=n("pA"),avg=promoAverage(t,a),o=model(avg,cost,px,fee)';assert.ok(current.includes(promoCore)&&base.includes(promoCore),'promotion calculation source unchanged');
const reverseFormula=html=>html.match(/function calcR\(\)\{([\s\S]*?);\$\("rRows"\)\.innerHTML=rows\(o\)/)?.[1];
assert.ok(reverseFormula(current));assert.equal(reverseFormula(current),reverseFormula(base),'reverse formula unchanged');
assert.equal(current.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1],base.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1]);
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html');if(!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']}),page=await context.newPage(),errors=[];
 page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
 await page.goto(`http://127.0.0.1:${server.address().port}/index.html`,{waitUntil:'networkidle'});await page.locator('[data-tab="scenario"]').click();
 const summary=page.locator('#scenarioSummary'),row=name=>summary.locator(`[data-plan="${name}"]`),rate=async name=>Number((await page.locator(`#scenarioResults .scenario-card:has(h3:text-is("方案 ${name}")) .scenario-final b`).innerText()).match(/([\d.]+)%/)[1]);
 assert.match(await summary.innerText(),/資料不足/);assert.equal(await summary.locator('[data-plan]').count(),3);
 await page.locator('#sProduct').fill('65010209');await page.locator('#sPriceA').fill('62');await page.locator('#sPrice').fill('77');await page.locator('#sPriceC').fill('90');
 assert.equal(await page.locator('[id^="sPromo"]').count(),0,'A/B/C have no extra-fee inputs');
 const existingCards=await page.locator('#scenarioResults .scenario-card').allInnerTexts(),a=await rate('A'),b=await rate('B'),c=await rate('C');
 const scenarioValues=await page.evaluate(()=>['A','B','C'].map((name,index)=>{const card=[...document.querySelectorAll('#scenarioResults .scenario-card')][index],marginText=card.querySelector('.scenario-final b').innerText,profitText=[...card.querySelectorAll('.scenario-metric')].find(row=>row.querySelector('span').textContent==='中科毛利額').querySelector('b').innerText,price=Number(document.getElementById(['sPriceA','sPrice','sPriceC'][index]).value),cost=Number(document.getElementById('sCost').value),front=Number(document.getElementById('sPx').textContent.replace('%',''))/100,fee=Number(document.getElementById('sFee').value)/100,ship=price/1.05*(1-front),profit=ship*(1-fee)-cost;return{name,shownProfit:Number(profitText.match(/([\d.]+) 元/)[1]),shownMargin:Number(marginText.match(/([\d.]+)%/)[1]),expectedProfit:profit,expectedMargin:profit/ship*100}}));
 for(const value of scenarioValues){assert.ok(Math.abs(value.shownProfit-value.expectedProfit)<0.005,value.name+' company fee applied exactly once to profit');assert.ok(Math.abs(value.shownMargin-value.expectedMargin)<0.005,value.name+' company fee applied exactly once to margin')}
 assert.doesNotMatch(await page.locator('#scenarioResults').innerText(),/促銷費用|額外費用/);
 assert.ok(a<b&&b<c);assert.match(await summary.locator('#scenarioSummaryHighest').innerText(),/C/);
 assert.match(await row('A').innerText(),new RegExp(a.toFixed(2)));
 const pointValue=text=>Number(text.match(/\+([\d.]+) 個百分點/)[1]);
 assert.ok(Math.abs(pointValue(await row('B').innerText())-(b-a))<0.005,'B percentage-point delta');
 assert.ok(Math.abs(pointValue(await row('C').innerText())-(c-a))<0.005,'C percentage-point delta');
 assert.match(await summary.locator('#scenarioSummaryThreshold').innerText(),/中科毛利門檻：37%/);
 assert.match(await summary.locator('#scenarioSummaryThreshold').innerText(),/B、C 已達門檻/);
 assert.match(await summary.locator('#scenarioSummaryThreshold').innerText(),/A 尚未達門檻/);
 assert.match(await summary.locator('#scenarioSummaryDetails').textContent(),/全聯前毛 26\.18%（三方案相同）/);
 assert.match(await summary.locator('#scenarioSummaryDetails').textContent(),/售價較 A：B \+\$15\.00、C \+\$28\.00/);
 await summary.locator('#copyScenarioSummary').click();const copied=await page.evaluate(()=>navigator.clipboard.readText());
 assert.match(copied,/【方案比較】/);assert.match(copied,/商品：OP無雙酚A鋁箔800公分-12入/);assert.match(copied,/B 方案：中科毛利率（費用後）/);assert.ok(Math.abs(pointValue(copied)-(b-a))<0.005);assert.match(copied,/目前設定中科毛利門檻：37%/);assert.doesNotMatch(copied,/促銷費用|額外費用/);
 assert.deepEqual(await page.locator('#scenarioResults .scenario-card').allInnerTexts(),existingCards,'copy/summary cannot alter A/B/C cards');
 await page.locator('#sFee').fill('15');const bAfterFee=await rate('B');assert.ok(bAfterFee<b,'shared company fee changes existing result');assert.match(await row('B').innerText(),new RegExp(bAfterFee.toFixed(2)));assert.ok(Math.abs(pointValue(await row('B').innerText())-(bAfterFee-await rate('A')))<0.005);await page.locator('#sFee').fill('10.95');
 await page.locator('#sCost').fill('24.50');assert.match(await summary.locator('#scenarioSummaryDetails').textContent(),/成本 \$24\.50（共用）/);assert.match(await page.locator('#scenarioResults .scenario-card').first().innerText(),/商品成本\s*24\.50 元/);await page.locator('#sCost').fill('25.22');
 await page.locator('#sPriceC').fill('');assert.match(await row('C').innerText(),/資料不足/);assert.ok(!(await row('C').innerText()).includes('0.0%'));assert.match(await summary.locator('#scenarioSummaryHighest').innerText(),/B/);
 await page.locator('#sPriceC').fill('90');await page.locator('#sPrice').fill('62');assert.match(await row('B').innerText(),/與 A 方案持平/);assert.match(await row('B').innerText(),/0\.0 個百分點/);
 await page.locator('#sPriceC').fill('62');assert.match(await summary.locator('#scenarioSummaryHighest').innerText(),/A、B、C/,'existing tied-highest badges drive the summary');
 await page.locator('#sPriceC').fill('90');
 await page.locator('#sPrice').fill('60');assert.match(await row('B').innerText(),/低於 A 方案/);assert.match(await row('B').innerText(),/−[\d.]+ 個百分點/);
 await page.locator('#sPrice').fill('77');await page.locator('[data-tab="calc"]').click();await page.locator('#thresholdSettings').evaluate(element=>{element.open=true});await page.locator('#excellentMargin').fill('50');await page.locator('#targetMargin').fill('45');await page.locator('[data-tab="scenario"]').click();assert.match(await summary.locator('#scenarioSummaryThreshold').innerText(),/中科毛利門檻：45%/);assert.match(await summary.locator('#scenarioSummaryThreshold').innerText(),/C 已達門檻/);await summary.locator('#copyScenarioSummary').click();assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/目前設定中科毛利門檻：45%/);
 await page.locator('#sProduct').fill('OP天然棉紗布(3片入)');for(const name of ['A','B','C'])assert.match(await row(name).innerText(),/資料不足/);assert.match(await summary.locator('#scenarioSummaryHighest').innerText(),/資料不足/);assert.ok(!(await summary.innerText()).includes('26.18%'),'old product front margin is not reused');
 await page.locator('#sProduct').fill('65010209');await page.locator('[data-tab="calc"]').click();await page.locator('#cProduct').fill('OP指尖強化手套-薰衣紫M');await page.locator('[data-tab="scenario"]').click();assert.match(await summary.locator('#scenarioSummaryDetails').textContent(),/26\.18%/,'other tab selection cannot change scenario product');
 const before=await page.locator('#scenarioResults').innerText();for(const tab of ['calc','reverse','promo','basis','campaign','scenario'])await page.locator(`[data-tab="${tab}"]`).click();assert.equal(await page.locator('#scenarioResults').innerText(),before);
 assert.doesNotMatch(await summary.innerText(),/推薦|最佳方案|應採用|一定要/);
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:undefined,configurable:true}));await summary.locator('#copyScenarioSummary').click();assert.match(await summary.locator('#scenarioSummaryFeedback').innerText(),/已複製|無法自動複製/,'clipboard fallback or a clear browser-permission message');
 await page.setViewportSize({width:390,height:844});await summary.screenshot({path:path.join(root,'tests/scenario-summary-mobile.png')});
 const viewports=[[320,568],[360,800],[375,667],[390,844],[393,852],[430,932],[768,1024],[820,1180],[1024,768],[1280,720],[1366,768],[1440,900],[1920,1080],[844,390]],rwd=[];
 for(const [width,height] of viewports){await page.setViewportSize({width,height});const status=await page.evaluate(()=>({overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),buttonHeight:document.querySelector('#copyScenarioSummary').getBoundingClientRect().height}));assert.equal(status.overflow,0,width+' overflow');assert.ok(status.buttonHeight>=44,width+' tap target');rwd.push(width+'x'+height)}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',percentagePoints:{a,b,c,bMinusA:b-a,cMinusA:c-a},highest:'C',threshold:'37% / 45%',missing:'PASS',copy:'PASS',formulaUnchanged:'PASS',otherTabs:'PASS',rwd,maximumOverflow:0,consoleErrors:errors},null,2));await browser.close();server.close();
})().catch(error=>{console.error(error);server.close();process.exit(1)});
