const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),config=JSON.parse(fs.readFileSync(path.join(root,'product-catalog.json'),'utf8'));
const ids=new Set();
for(const p of config.products){if(!p.id||ids.has(p.id)||!config.categories[p.category]||!Array.isArray(p.aliases))throw Error('Invalid catalog product: '+p.id);ids.add(p.id);}
fs.writeFileSync(path.join(root,'product-catalog.js'),'// Generated by scripts/build_product_catalog.cjs; edit product-catalog.json.\nconst PX_CATALOG_CONFIG = '+JSON.stringify(config)+';\n');
