/* Usage: node scripts/import_px_promos.cjs workbook.xlsx --python python.exe [--year 2027] */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const core=require('../px-promo-core.js');
const root=path.resolve(__dirname,'..');
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;
function importRows(source,master,existing={products:[]}){
 const issues=[...source.issues],products=new Map(existing.products.map(p=>[p.productName,JSON.parse(JSON.stringify(p))])),seen=new Set(),methods={CODE:0,BARCODE:0,NAME:0};let success=0;
 const issue=(severity,row,reason,extra={})=>issues.push({severity,sheet:row.sheet,row:row.row,reason,...extra});
 for(const row of source.rows){
  const code=core.identifier(row.raw.code),barcode=core.identifier(row.raw.barcode),productName=core.clean(row.raw.name);
  for(const [key,val] of Object.entries({code,barcode,name:productName}))if(!val)issue('warning',row,'MISSING_'+key.toUpperCase());
  if(Object.entries(row.raw).some(([key,val])=>String(val??'')!==({code,barcode,name:productName}[key])))issue('warning',row,'NORMALIZED_WHITESPACE');
  let matches=master.filter(p=>code&&p.code===code),method='CODE';
  if(!matches.length){matches=master.filter(p=>barcode&&p.barcode===barcode);method='BARCODE';}
  if(!matches.length){matches=master.filter(p=>core.name(p.name)===core.name(productName));method='NAME';}
  if(matches.length!==1){issue('error',row,matches.length?'AMBIGUOUS_PRODUCT':'UNMATCHED_PRODUCT',{code,barcode,productName});continue;}
  const match=matches[0];
  if((code&&match.code&&code!==match.code)||(barcode&&match.barcode&&barcode!==match.barcode)){issue('error',row,'IDENTIFIER_CONFLICT',{code,barcode,productName});continue;}
  if(method==='NAME')issue('warning',row,'NAME_FALLBACK',{productName});
  if(seen.has(match.name))issue('warning',row,'DUPLICATE_PRODUCT',{productName});seen.add(match.name);methods[method]++;
  let item=products.get(match.name)||{productId:match.code,barcode:match.barcode,productName:match.name,periods:{}};
  for(const period of row.periods){
   const {column,rawText,...dates}=period;
   if(!validDate(dates.startDate)||!validDate(dates.endDate)||dates.startDate>dates.endDate){issue('error',row,'INVALID_DATE',{period:dates.id});continue;}
   const parsed=core.parse(rawText);parsed.warnings.forEach(reason=>issue('warning',row,reason,{period:dates.id,rawText}));
   if(parsed.promotions.some(p=>p.promotionPrice!==null&&!Number.isFinite(p.promotionPrice))||(/\$\s*[^\d\s]/.test(core.clean(rawText))))issue('error',row,'NON_NUMERIC_PRICE',{period:dates.id,rawText});
   const value={...dates,campaignType:parsed.campaignType,promotions:parsed.promotions,sourceText:core.clean(rawText),sourceRow:row.row,sourceSheet:row.sheet,matchMethod:method};
   const old=item.periods[dates.id];
   if(old&&JSON.stringify([old.campaignType,old.promotions])!==JSON.stringify([value.campaignType,value.promotions])){issue('error',row,'PERIOD_PRICE_CONFLICT',{productName:match.name,period:dates.id});continue;}
   item.periods[dates.id]=value;success++;
  }
  products.set(match.name,item);
 }
 return {data:{schemaVersion:1,products:[...products.values()]},report:{sourceProducts:source.rows.length,importedProducts:seen.size,successfulPeriods:success,matchMethods:methods,warningCount:issues.filter(i=>i.severity==='warning').length,errorCount:issues.filter(i=>i.severity==='error').length,issues}};
}
if(require.main===module){
 const file=process.argv[2],arg=key=>process.argv[process.argv.indexOf(key)+1],python=process.argv.includes('--python')?arg('--python'):'python';
 const run=spawnSync(python,['-X','utf8',path.join(__dirname,'read_px_promos.py'),file,...(process.argv.includes('--year')?[arg('--year')]:[])],{encoding:'utf8'});
 if(run.status!==0)throw Error(run.stderr);
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),master=vm.runInNewContext(html.match(/const PX_Q3_PRODUCTS\s*=\s*(\[[\s\S]*?\]);/)[1]);
 const source=JSON.parse(run.stdout),dataFile=path.join(root,'px-promo-prices.json'),existing=fs.existsSync(dataFile)?JSON.parse(fs.readFileSync(dataFile,'utf8')):{products:[]},result=importRows(source,master,existing);
 result.data.sourceFile=path.basename(file);result.data.sourceSHA256=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');result.data.dataVersion=[...new Set(core.periods(result.data).map(p=>p.id.slice(0,7)))].join(' / ');
 result.report.sourceFile=result.data.sourceFile;result.report.sourceSHA256=result.data.sourceSHA256;result.report.rawRows=source.rows;
 fs.writeFileSync(dataFile,JSON.stringify(result.data,null,2)+'\n');fs.writeFileSync(path.join(root,'px-promo-prices.js'),'// Generated by scripts/import_px_promos.cjs; do not edit prices manually.\nconst PX_PROMO_PRICES = '+JSON.stringify(result.data)+';\n');fs.writeFileSync(path.join(root,'PX_PROMO_VALIDATION.json'),JSON.stringify(result.report,null,2)+'\n');
 console.log(JSON.stringify({...result.report,issues:undefined,rawRows:undefined},null,2));
}
module.exports={importRows};
